name: Ostad CI/CD Pipeline

on:
  push:
    branches:
      - Main
      - dev
  pull_request:
    branches:
      - Main

jobs:
  setup-nginx:
    runs-on: self-hosted
  
    steps:
        - name: Install The nginx
          run: sudo apt install nginx -y

