name: Ostad CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  read_the_file:
    runs-on: self-hosted
    steps:
      - name: Install the nginx
        run: sudo apt-get install nginx -y
      
